# Generated by Django 4.1.1 on 2022-10-07 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pers_nombre', models.CharField(max_length=30)),
                ('pers_segundonombre', models.CharField(max_length=30)),
                ('pers_apellido', models.CharField(max_length=20)),
                ('pers_segundoapellido', models.CharField(max_length=20)),
                ('pers_telefono', models.CharField(max_length=10)),
                ('pers_correo', models.CharField(max_length=30)),
                ('tiposexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestra.tablamaestra')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_nacionalidad', models.CharField(max_length=20)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.personas')),
                ('tipoempleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestra.tablamaestra')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clie_nacionalidad', models.CharField(max_length=20)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.personas')),
                ('tipocliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestra.tablamaestra')),
            ],
        ),
    ]
