# Generated by Django 4.1.2 on 2022-10-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestra', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='tipodocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipodocumento', to='maestra.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='tiposexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiposexo', to='maestra.tablamaestra'),
        ),
    ]
